### PR TITLE
Backend Server is Up

### PR DESCRIPTION
**Pull request by terryzfeng**
Backend, please review this PR.

Backend has now shifted to the Admin SDK. The config.js is still there for Firebase storage purposes but most Firestore functions should still be the same with Admin.

README has been updated for the new Service Key stuff.

Now that server has been written, once your functions have been tested (node), you can connect them to the Routes and test them with Postman. (More on that Monday)

### CODE REVIEW

**Comment by vukRadovanovic** [comment]
Looks good!

**Comment by terryzfeng** [comment]
Are we all good for this request?

**Review by evanjserrano — APPROVED** [review]
Looks gucci

**Comment by evanjserrano** [comment]
I think we're good to merge

**Pull request merged**
